Repository gambler-iOS/gambler, pull requests merged in 2024-02, with the labels that each got.

#16 Feat: Model 구현 #15
  .gitignore
  Projects/App/Sources/Foundation/.gitkeep
  Projects/App/Sources/Foundation/Protocols/AvailableAggregateReview.swift
  Projects/App/Sources/Foundation/Protocols/AvailableFirebase.swift
  Projects/App/Sources/Model/.gitkeep
  Projects/App/Sources/Model/AgreeTerms.swift
  Projects/App/Sources/Model/Complain.swift
  Projects/App/Sources/Model/EventBanner.swift
  Projects/App/Sources/Model/Game.swift
  Projects/App/Sources/Model/Notice.swift
  Projects/App/Sources/Model/Report.swift
  Projects/App/Sources/Model/Review.swift
  Projects/App/Sources/Model/SearchHistory.swift
  Projects/App/Sources/Model/Shop.swift
  Projects/App/Sources/Model/User.swift
Labels: enhancement

#20 Feat: 공통 모듈 뷰
  Projects/App/Resources/Asset.xcassets/heartGray.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/heartGray.imageset/heartGray.png
  Projects/App/Resources/Asset.xcassets/tabHome.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabHome.imageset/tabHome.png
  Projects/App/Resources/Asset.xcassets/tabHomeSelected.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabHomeSelected.imageset/tabHomeSelected.png
  Projects/App/Resources/Asset.xcassets/tabMap.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabMap.imageset/tabMap.png
  Projects/App/Resources/Asset.xcassets/tabMapSelected.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabMapSelected.imageset/tabMapSelected.png
  Projects/App/Resources/Asset.xcassets/tabProfile.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabProfile.imageset/tabProfile.png
  Projects/App/Resources/Asset.xcassets/tabProfileSelected.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabProfileSelected.imageset/tabProfileSelected.png
  Projects/App/Resources/Asset.xcassets/tabSearch.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabSearch.imageset/tabSearch.png
  Projects/App/Resources/Asset.xcassets/tabSearchSelected.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/tabSearchSelected.imageset/tabSearchSelected.png
  Projects/App/Sources/Common/CardItemView.swift
  Projects/App/Sources/Common/ChipView.swift
  Projects/App/Sources/Common/Constants.swift
  Projects/App/Sources/Common/GameGridItemView.swift
  Projects/App/Sources/Common/GameListItemView.swift
  Projects/App/Sources/Common/HeartCellView.swift
  Projects/App/Sources/Common/ReviewRatingCellView.swift
  Projects/App/Sources/Common/SearchBarView.swift
  Projects/App/Sources/Common/SegmentTabView.swift
  Projects/App/Sources/Common/ShopListCellView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Foundation/Protocols/FilterType.swift
  Projects/App/Sources/Model/Game.swift
  Projects/App/Sources/Model/Shop.swift
Labels: ✨ Feature, 🧑🏻‍💻 cha-nyeong

#26 Feat: ReviewRatingCellView 매개변수 rating:Double 값 받는 것으로 변경
  Projects/App/Sources/Common/CardItemView.swift
  Projects/App/Sources/Common/GameGridItemView.swift
  Projects/App/Sources/Common/GameListItemView.swift
  Projects/App/Sources/Common/ReviewRatingCellView.swift
  Projects/App/Sources/Common/ShopListCellView.swift
Labels: hyomyeong, 🔧Fix

#24 Feat: 공통뷰 개발
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/Common/BorderView.swift
  Projects/App/Sources/Common/ItemButtonSetView.swift
  Projects/App/Sources/Common/MyPageFilter.swift
  Projects/App/Sources/Common/ReviewListCellView.swift
  Projects/App/Sources/Common/SectionHeaderView.swift
Labels: ⚙ Setting, ✨ Feature, 🌈 daye

#33 Feat: HomeView 인기매장과 신규매장 리스트 화면 구현
  Projects/App/Sources/Feature/Home/View/HomeShopListView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailView.swift
Labels: ✨ Feature, hyomyeong

#29 Fix : 채영님의 디자인 확인 이후 수정
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/CardItemView.swift
  Projects/App/Sources/Common/ChipView.swift
  Projects/App/Sources/Common/GameCategoryCellView.swift
  Projects/App/Sources/Common/GameGridItemView.swift
  Projects/App/Sources/Common/GameListItemView.swift
  Projects/App/Sources/Common/SearchBarView.swift
  Projects/App/Sources/Common/SegmentTabView.swift
  Projects/App/Sources/Common/TabBarView.swift
Labels: 🧑🏻‍💻 cha-nyeong, 🔧Fix

#36 Feat: SearchMainView 추가
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/ChipView.swift
  Projects/App/Sources/Common/SearchBarView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/Search/RecentKeywordView.swift
  Projects/App/Sources/Feature/Search/SearchMainView.swift
  Projects/App/Sources/Foundation/Layout/ChipLayout.swift
  Projects/App/Sources/Model/SearchKeyword.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨ Feature, 🧑🏻‍💻 cha-nyeong

#48 Feat/#37 검색 결과 뷰 추가
  Projects/App/Sources/Common/GameListItemView.swift
  Projects/App/Sources/Common/SectionHeaderView.swift
  Projects/App/Sources/Feature/Search/View/SearchResultView.swift
  Projects/App/Sources/Feature/Search/ViewModel/SearchViewModel.swift
Labels: ✨ Feature, 🧑🏻‍💻 cha-nyeong

#42 Feat: HomeView 이벤트배너 구현, stickyHeader 구현, 각 리스트에서 SectionHeaderView 사용하도록 변경
  Projects/App/Sources/Common/SectionHeaderView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/EventBanner/View/EventBannerView.swift
  Projects/App/Sources/Feature/EventBanner/ViewModel/EventBannerViewModel.swift
  Projects/App/Sources/Feature/Home/View/HomeGameCardHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeGameCategoryHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeGameGridView.swift
  Projects/App/Sources/Feature/Home/View/HomeShopListView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Foundation/Protocols/AvailableFirebase.swift
  Projects/App/Sources/Service/SampleCodeView.swift
Labels: ✨ Feature, hyomyeong

#43 Feat: MyPageView 추가
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/BackButton.swift
  Projects/App/Sources/Common/CircleImageView.swift
  Projects/App/Sources/Common/ReviewDetailCellView.swift
  Projects/App/Sources/Common/ReviewListCellView.swift
  Projects/App/Sources/Common/SegmentTabView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/MyPage/View/AboutDevelopersView.swift
  Projects/App/Sources/Feature/MyPage/View/AnnouncementsView.swift
  Projects/App/Sources/Feature/MyPage/View/CustomerServiceView.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyLikesView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/MyReviewsView.swift
  Projects/App/Sources/Feature/MyPage/View/NotificationSettingView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/View/TermsOfUseView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Model/Review.swift
  Projects/App/Sources/Model/User.swift
Labels: ✨ Feature, 🐶 sunghun

#55 리뷰 디테일 뷰 및 리뷰 작성 뷰 구현
  Projects/App/Resources/Asset.xcassets/Closed.imageset/Closed.png
  Projects/App/Resources/Asset.xcassets/Closed.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/Plus.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/Plus.imageset/Plus.png
  Projects/App/Resources/Asset.xcassets/Success.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/Success.imageset/Success.png
  Projects/App/Resources/Asset.xcassets/emptyStar.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/emptyStar.imageset/emptyStar.png
  Projects/App/Resources/Asset.xcassets/halfStar.imageset/1-2.png
  Projects/App/Resources/Asset.xcassets/halfStar.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/searchClosed.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/searchClosed.imageset/Search Closed.png
  Projects/App/Resources/Asset.xcassets/searchClosedPrimary.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/searchClosedPrimary.imageset/searchClosedPrimary.png
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/Common/AddImageView.swift
  Projects/App/Sources/Common/CTAButton.swift
  Projects/App/Sources/Common/RectangleImageView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Common/TextEditorView.swift
  Projects/App/Sources/Extension/UIApplication+Extension.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/Review/View/RatingView.swift
  Projects/App/Sources/Feature/Review/View/ReviewDetailView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
Labels: ✨ Feature, 🐶 sunghun

#60 Model 전체적으로 정검 및 수정, 그에 따른 더미데이터 에러 코드 수정
  Projects/App/Sources/Feature/EventBanner/ViewModel/EventBannerViewModel.swift
  Projects/App/Sources/Feature/Game/View/GameDetailInfoView.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameDetailViewModel.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameListViewModel.swift
  Projects/App/Sources/Feature/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Model/Complain.swift
  Projects/App/Sources/Model/EventBanner.swift
  Projects/App/Sources/Model/Game.swift
  Projects/App/Sources/Model/Notice.swift
  Projects/App/Sources/Model/Report.swift
  Projects/App/Sources/Model/SearchHistory.swift
  Projects/App/Sources/Model/Shop.swift
  Projects/App/Sources/Model/User.swift
Labels: 🧑🏻‍💻 cha-nyeong, 🐶 sunghun, hyomyeong, 🌈 daye, 🔧Fix
