Repository gambler-iOS/gambler, pull requests merged in 2024-04, with the labels that each got.

#112 Fix: 공통뷰인 ItemButtonSetView 에 찜하기와 리뷰 로직 구현, 게임디테일에서 찜하기 버튼 안눌러지는 문제 수정
  Projects/App/Sources/Common/ItemButtonSetView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailInfoView.swift
Labels: hyomyeong, 🔧Fix

#119 홈,게임 관련 테스트플라이트 테스트에서 수정사항 구현
  Projects/App/Sources/Common/SectionHeaderView.swift
  Projects/App/Sources/Feature/EventBanner/View/EventBannerView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailInfoView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailReviewHScrollView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailView.swift
  Projects/App/Sources/Feature/Game/View/GameSimilarHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeGameCardHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeGameGenreHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/Home/ViewModel/HomeViewModel.swift
Labels: 🐞 BugFix, ✨ Feature, hyomyeong

#114 Feat: 마이페이지, 로그인 관련 테스트플라이트 점검 사항 보강(필수 위주)
  Projects/App/Resources/Asset.xcassets/DiceLogo.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/DiceLogo.imageset/DiceLogo.png
  Projects/App/Resources/Asset.xcassets/logo.imageset/logo.png
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/Common/CustomToastView.swift
  Projects/App/Sources/Common/WKView.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/View/RegisterTermsOfUseView.swift
  Projects/App/Sources/Feature/Login/View/RegistrationView.swift
  Projects/App/Sources/Feature/Login/View/TextFieldView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/AboutDevelopersView.swift
  Projects/App/Sources/Feature/MyPage/View/AnnouncementsView.swift
  Projects/App/Sources/Feature/MyPage/View/CustomerServiceView.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyLikesView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageSignedOutView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/MyWebView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/View/TermsOfUseView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Model/Notice.swift
  Projects/App/Sources/Network/Firebase/StorageManager.swift
  Projects/App/Sources/Service/AppNavigationPath.swift
  Projects/App/Sources/Service/AuthService.swift
  Projects/App/Sources/Service/KakaoAuthService.swift
Labels: ⚙ Setting, ✨ Feature, 🐶 sunghun

#123 GameDetailView 평점과 리뷰 개수 바로 갱신되도록 수정, 이벤트배너에 적합한 사이트 정보 입력
  Projects/App/Sources/Feature/Game/View/GameDetailView.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameDetailViewModel.swift
Labels: 🐞 BugFix, ✨ Feature, hyomyeong

#118 매장 상세뷰의 테스트 플라이트 수정
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/BackButton.swift
  Projects/App/Sources/Common/HeartCellView.swift
  Projects/App/Sources/Common/ItemButtonSetView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailReviewHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/View/RegisterTermsOfUseView.swift
  Projects/App/Sources/Feature/Map/View/MapView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingCellView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageSignedOutView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/CustomModalView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Feature/Search/View/SearchMainView.swift
  Projects/App/Sources/Feature/Search/View/SearchShopListView.swift
  Projects/App/Sources/Feature/Shop/View/MapContainer/KakaoMapDefaultView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailHeaderView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailInfoView.swift
  Projects/App/Sources/Feature/Shop/View/ShopListView.swift
  Projects/App/Sources/Feature/Shop/ViewModel/ShopDetailViewModel.swift
Labels: 🐞 BugFix, ✨ Feature, 🧑🏻‍💻 cha-nyeong

#122 테스트플라이트 추가사항 (지도, 공지사항)
  Projects/App/Sources/Common/WKView.swift
  Projects/App/Sources/Common/WebView.swift
  Projects/App/Sources/Feature/Map/Extension/KakaoMapView+Extension.swift
  Projects/App/Sources/Feature/Map/View/KakaoMapView.swift
  Projects/App/Sources/Feature/Map/View/MapView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingView.swift
  Projects/App/Sources/Feature/Map/View/SubView/MapSheetView.swift
  Projects/App/Sources/Feature/Map/ViewModel/MapViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/AnnouncementsView.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/AnnouncementsViewModel.swift
  Projects/App/Sources/Model/Constants.swift
  Projects/App/Sources/Network/Firebase/FirebaseManager.swift
Labels: ✨ Feature, 🌈 daye, 🔧Fix

#124 MyPage, RegisterTermsOfUseView 웹뷰 주소 연결 및 밑줄 수정
  Projects/App/Sources/Common/HeartCellView.swift
  Projects/App/Sources/Common/ItemButtonSetView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailView.swift
  Projects/App/Sources/Feature/Login/View/CheckBox.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/View/RegisterTermsOfUseView.swift
  Projects/App/Sources/Feature/Login/View/RegistrationView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/AboutDevelopersView.swift
  Projects/App/Sources/Feature/MyPage/View/MyLikesView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Feature/Review/View/ReviewDetailView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailInfoView.swift
  Projects/App/Sources/Network/Firebase/StorageManager.swift
  Projects/App/Sources/Service/AppNavigationPath.swift
Labels: ✨ Feature, 🐶 sunghun, 🔧Fix
