Repository gambler-iOS/gambler, pull requests merged in 2024-03, with the labels that each got.

#63 Feat: MapView
  Projects/App/Resources/Asset.xcassets/Location.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/Location.imageset/Location.png
  Projects/App/Resources/Asset.xcassets/myLocation.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/myLocation.imageset/My location.png
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/Constants.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Extension/UIImage+Extension.swift
  Projects/App/Sources/Feature/Map/Extension/KakaoMapView+Extension.swift
  Projects/App/Sources/Feature/Map/View/KakaoMapView.swift
  Projects/App/Sources/Feature/Map/View/MapView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingCellView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingView.swift
  Projects/App/Sources/Feature/Map/View/SubView/MapSheetView.swift
  Projects/App/Sources/Feature/Shop/ViewModel/ShopStore.swift
  Projects/App/Sources/Model/Shop.swift
  Tuist/Dependencies.swift
Labels: ✨ Feature, 🌈 daye

#58 Tuist dependencies setting SPM 방식으로 변경
  Projects/App/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Dependency+SPM.swift
Labels: ⚙ Setting, 🐞 BugFix, hyomyeong

#67 마이페이지 나머지 뷰 PR
  Projects/App/Resources/Asset.xcassets/appleLogo.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/appleLogo.imageset/apple.png
  Projects/App/Resources/Asset.xcassets/googleLogo.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/googleLogo.imageset/kakaotalk.png
  Projects/App/Resources/Asset.xcassets/kakaotalkLogo.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/kakaotalkLogo.imageset/kakaotalk.png
  Projects/App/Sources/Common/WebView.swift
  Projects/App/Sources/Feature/MyPage/View/AnnouncementsView.swift
  Projects/App/Sources/Feature/MyPage/View/CustomerServiceView.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/NotificationSettingView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/DropDownMemuView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/PluginCellView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/ProfileButtonView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/TitleAndBoxView.swift
  Projects/App/Sources/Feature/MyPage/View/TermsOfUseView.swift
  Projects/App/Sources/Model/Notice.swift
Labels: ✨ Feature, 🌈 daye

#68 SSO 로그인
  Projects/App/Project.swift
  Projects/App/Resources/Asset.xcassets/appleLogin.imageset/Apple.png
  Projects/App/Resources/Asset.xcassets/appleLogin.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/checkBox.imageset/Check box2.png
  Projects/App/Resources/Asset.xcassets/checkBox.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/googleLogin.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/googleLogin.imageset/Google.png
  Projects/App/Resources/Asset.xcassets/kakaoLogin.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/kakaoLogin.imageset/Kakao.png
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/App/AppDelegate.swift
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/Login/View/CheckBox.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/View/RegisterTermsOfUseView.swift
  Projects/App/Sources/Feature/Login/View/RegistrationView.swift
  Projects/App/Sources/Feature/Login/View/TextFieldView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyLikesView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/MyReviewsView.swift
  Projects/App/Sources/Feature/Review/View/ReviewDetailView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Model/User.swift
  Projects/App/Sources/Network/Firebase/FirebaseManager.swift
  Projects/App/Sources/Network/Firebase/StorageManager.swift
  Projects/App/Sources/Service/AppleAuthService.swift
  Projects/App/Sources/Service/AuthService.swift
  Projects/App/Sources/Service/GoogleAuthService.swift
  Projects/App/Sources/Service/KakaoAuthService.swift
Labels: 📬 API, ✨ Feature, 🐶 sunghun

#81 FirebaseManager 수정 및 추가 구현, Game 모델 변경, GameListViewModel 과 GameDetailViewModel firebase 통신 구현
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/Constants.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailView.swift
  Projects/App/Sources/Feature/Game/View/GameListView.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameDetailViewModel.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameListViewModel.swift
  Projects/App/Sources/Feature/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Feature/Login/View/RegistrationView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Model/Game.swift
  Projects/App/Sources/Network/Firebase/FirebaseManager.swift
  Projects/App/Sources/Network/Firebase/StorageManager.swift
Labels: ✨ Feature, hyomyeong, 🔧Fix

#72 Map, 탭바 배경색 사라지는 이슈 해결
  Projects/App/Project.swift
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/Map/Extension/KakaoMapView+Extension.swift
  Projects/App/Sources/Feature/Map/View/KakaoMapView.swift
  Projects/App/Sources/Feature/Map/View/MapView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingView.swift
  Projects/App/Sources/Feature/Map/View/SubView/MapSheetView.swift
Labels: ✨ Feature, 🌈 daye

#87 마이페이지 세부사항
  Projects/App/Sources/Common/AddImageView.swift
  Projects/App/Sources/Common/ClearBackgroundView.swift
  Projects/App/Sources/Common/Constants.swift
  Projects/App/Sources/Common/CustomToastView.swift
  Projects/App/Sources/Feature/MyPage/View/CustomerServiceView.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/NotificationSettingView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/CustomModalView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/PluginCellView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/ProfileButtonView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/ComplainViewModel.swift
  Projects/App/Sources/Feature/Review/View/ReviewDetailView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Network/Firebase/StorageManager.swift
Labels: ✨ Feature, 🌈 daye

#89 Feat/#47 shop list,shop detail view
  Projects/App/Sources/Common/GameListItemView.swift
  Projects/App/Sources/Common/HeartCellView.swift
  Projects/App/Sources/Common/ItemButtonSetView.swift
  Projects/App/Sources/Common/ReviewListCellView.swift
  Projects/App/Sources/Common/ShopListCellView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Extension/View+Extension.swift
  Projects/App/Sources/Feature/Game/View/GameListView.swift
  Projects/App/Sources/Feature/Home/View/HomeShopListView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Feature/Search/View/RecentKeywordView.swift
  Projects/App/Sources/Feature/Search/View/SearchMainView.swift
  Projects/App/Sources/Feature/Shop/View/FullScreenImageView.swift
  Projects/App/Sources/Feature/Shop/View/MapContainer/KakaoMapDefaultView.swift
  Projects/App/Sources/Feature/Shop/View/MapContainer/KakaoStaticView.swift
  Projects/App/Sources/Feature/Shop/View/ShopCostDetailView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailHeaderView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailImageListView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailInfoView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailView.swift
  Projects/App/Sources/Feature/Shop/View/ShopListView.swift
  Projects/App/Sources/Feature/Shop/ViewModel/ImageItem.swift
  Projects/App/Sources/Feature/Shop/ViewModel/ShopListViewModel.swift
  Projects/App/Sources/Model/Shop.swift
Labels: ✨ Feature, 🧑🏻‍💻 cha-nyeong

#85 Home 과 EventBanner ViewModel Firebase 통신 구현
  Projects/App/Resources/Asset.xcassets/gameGenre/Contents.json
  Projects/App/Resources/Asset.xcassets/gameGenre/Fantasy.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/gameGenre/Fantasy.imageset/Fantasy.jpeg
  Projects/App/Sources/Common/CardItemView.swift
  Projects/App/Sources/Common/GameCategoryCellView.swift
  Projects/App/Sources/Common/GameGenreCellView.swift
  Projects/App/Sources/Common/GameGridItemView.swift
  Projects/App/Sources/Common/GameListItemView.swift
  Projects/App/Sources/Common/GameMiniGridItemView.swift
  Projects/App/Sources/Feature/EventBanner/View/EventBannerView.swift
  Projects/App/Sources/Feature/EventBanner/View/EventBannerWebView.swift
  Projects/App/Sources/Feature/EventBanner/ViewModel/EventBannerViewModel.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameListViewModel.swift
  Projects/App/Sources/Feature/Home/View/HomeGameGenreHScrollView.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/Home/ViewModel/HomeViewModel.swift
  Projects/App/Sources/Model/EventBanner.swift
  Projects/App/Sources/Model/Game.swift
Labels: ✨ Feature, hyomyeong, 🔧Fix

#90 SSO 관련 로직 및 뷰 + 마이페이지
  .firebaserc
  Projects/App/Project.swift
  Projects/App/Resources/Asset.xcassets/logo.imageset/Contents.json
  Projects/App/Resources/Asset.xcassets/logo.imageset/logo.png
  Projects/App/Resources/gambler-Info.plist
  Projects/App/Sources/Common/CircleImageView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Common/Toast.swift
  Projects/App/Sources/Extension/Date+Extension.swift
  Projects/App/Sources/Extension/String+Extension.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/View/RegisterTermsOfUseView.swift
  Projects/App/Sources/Feature/Login/View/RegistrationView.swift
  Projects/App/Sources/Feature/Login/View/TextFieldView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyLikesView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageSignedOutView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/MyReviewsView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/View/SubView/PluginCellView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Feature/Review/View/ReviewDetailView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Model/Shop.swift
  Projects/App/Sources/Model/User.swift
  Projects/App/Sources/Service/AppNavigationPath.swift
  Projects/App/Sources/Service/AppleAuthService.swift
  Projects/App/Sources/Service/AuthService.swift
  Projects/App/Sources/Service/GoogleAuthService.swift
  Projects/App/Sources/Service/KakaoAuthService.swift
Labels: 📬 API, ✨ Feature, 🐶 sunghun

#93 Map 데이터 연결
  Projects/App/Sources/Common/ItemButtonSetView.swift
  Projects/App/Sources/Common/ShopListCellView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Feature/Map/Extension/KakaoMapView+Extension.swift
  Projects/App/Sources/Feature/Map/View/KakaoMapView.swift
  Projects/App/Sources/Feature/Map/View/MapView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingCellView.swift
  Projects/App/Sources/Feature/Map/View/SubView/FloatingView.swift
  Projects/App/Sources/Feature/Map/View/SubView/MapSheetView.swift
  Projects/App/Sources/Feature/Map/ViewModel/MapViewModel.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailInfoView.swift
  Projects/App/Sources/Feature/Shop/ViewModel/ShopListViewModel.swift
  Projects/App/Sources/Feature/Shop/ViewModel/ShopStore.swift
  Projects/App/Sources/Model/Shop.swift
  Projects/App/Sources/Network/Firebase/FirebaseManager.swift
  Projects/App/Sources/Service/AppNavigationPath.swift
Labels: ✨ Feature, 🌈 daye

#102 Feat/#92 my page data
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/CustomLoadingView.swift
  Projects/App/Sources/Common/CustomToastView.swift
  Projects/App/Sources/Common/ReviewDetailCellView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Common/Toast.swift
  Projects/App/Sources/Extension/Date+Extension.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/View/RegisterTermsOfUseView.swift
  Projects/App/Sources/Feature/Login/View/RegistrationView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/CustomerServiceView.swift
  Projects/App/Sources/Feature/MyPage/View/ListItemView.swift
  Projects/App/Sources/Feature/MyPage/View/MyLikesView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageView.swift
  Projects/App/Sources/Feature/MyPage/View/MyReviewsView.swift
  Projects/App/Sources/Feature/MyPage/View/ProfileEditView.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/MyPageViewModel.swift
  Projects/App/Sources/Feature/MyPage/ViewModel/ProfileEditViewModel.swift
  Projects/App/Sources/Feature/Review/View/ReviewDetailView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
  Projects/App/Sources/Feature/Review/ViewModel/ReviewViewModel.swift
  Projects/App/Sources/Model/Review.swift
  Projects/App/Sources/Service/AppleAuthService.swift
  Projects/App/Sources/Service/AuthService.swift
  Projects/App/Sources/Service/GoogleAuthService.swift
  Projects/App/Sources/Service/KakaoAuthService.swift
Labels: 📬 API, ✨ Feature, 🐶 sunghun

#104 Feat/#83 search
  Projects/App/Project.swift
  Projects/App/Resources/Asset.xcassets/AppIcon.appiconset/1024px.png
  Projects/App/Resources/Asset.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Common/SearchBarView.swift
  Projects/App/Sources/Common/TabBarView.swift
  Projects/App/Sources/Extension/Algolia+Extension.swift
  Projects/App/Sources/Feature/Search/View/RecentKeywordView.swift
  Projects/App/Sources/Feature/Search/View/SearchGameListView.swift
  Projects/App/Sources/Feature/Search/View/SearchMainView.swift
  Projects/App/Sources/Feature/Search/View/SearchResultView.swift
  Projects/App/Sources/Feature/Search/View/SearchShopListView.swift
  Projects/App/Sources/Feature/Search/ViewController/MultiController.swift
  Projects/App/Sources/Feature/Search/ViewController/MultiSearchController.swift
  Projects/App/Sources/Feature/Shop/View/ShopCostDetailView.swift
  Projects/App/Sources/Feature/Shop/View/ShopDetailInfoView.swift
  Projects/App/Sources/Feature/Shop/View/ShopListView.swift
  Projects/App/Sources/Model/Constants.swift
  Projects/App/Sources/Model/Shop.swift
  Projects/App/Sources/Service/AppNavigationPath.swift
Labels: ✨ Feature, 🧑🏻‍💻 cha-nyeong

#107 Game 관련 NavigationPath 오류 수정, GameDetail 화면 리뷰 관련 문제 해결
  Projects/App/Sources/Common/ReviewListCellView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailReviewHScrollView.swift
  Projects/App/Sources/Feature/Game/View/GameDetailView.swift
  Projects/App/Sources/Feature/Game/View/GameListView.swift
  Projects/App/Sources/Feature/Game/View/GameSimilarHScrollView.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameDetailViewModel.swift
  Projects/App/Sources/Feature/Game/ViewModel/GameListViewModel.swift
  Projects/App/Sources/Feature/Home/View/HomeView.swift
  Projects/App/Sources/Feature/Review/View/WriteReviewView.swift
Labels: hyomyeong, 🔧Fix

#111 Fix/#105 game,home view,view model
  Projects/App/Sources/App/GamblerApp.swift
  Projects/App/Sources/Feature/Login/View/LoginView.swift
  Projects/App/Sources/Feature/Login/ViewModel/LoginViewModel.swift
  Projects/App/Sources/Feature/MyPage/View/CustomerServiceView.swift
  Projects/App/Sources/Feature/MyPage/View/MyPageSignedOutView.swift
  Projects/App/Sources/Service/AppleAuthService.swift
  Projects/App/Sources/Service/GoogleAuthService.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🐞 BugFix, ✨ Feature, 🐶 sunghun
